# Generated by Django 3.1.4 on 2020-12-30 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 30, 20, 37, 52, 998336, tzinfo=utc)),
        ),
    ]
