# Generated by Django 3.1.4 on 2021-01-03 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_auto_20201230_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 23, 23, 29, 180913, tzinfo=utc)),
        ),
    ]
