# Generated by Django 3.1.4 on 2021-01-04 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0003_auto_20210103_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 3, 22, 16, 732483, tzinfo=utc)),
        ),
    ]
