# Generated by Django 3.1.4 on 2021-01-05 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0005_auto_20210105_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='title',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 2, 11, 38, 785759, tzinfo=utc)),
        ),
    ]
